services:
  - docker

before_install:
  - docker build -t aloneinabyss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aloneinabyss/react-test npm test -- --coverage

after_success:
  - docker build -t aloneinabyss/multi-client -f ./client
  - docker build -t aloneinabyss/multi-nginx -f ./nginx
  - docker build -t aloneinabyss/multi-server -f ./server
  - docker build -t aloneinabyss/multi-worker -f ./worker
